<?php

namespace rendu\CinemaBundle\Repository;

/**
 * realisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class realisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
